model = "ltcnn"
dataset = "cifar10"
task = "cls"
batch_size = 64
accelerator = "gpu"
seed = 42

[search.search_space]
name = "ltcnn/architecture"

[search.search_space.setup]
n_values = [2, 3, 4, 5, 6]
conv_channels_options = [[8, 16], [16, 32], [32, 64]]
kernel_size_options = [3, 5]
ff_hidden_sizes_options = [[200, 100], [500, 200]]
bit_depth_options = [2, 3, 4]
Q_options = [0, 2, 4]

encoding = "quantization"
in_channels = 3
num_classes = 10
image_size = 32

[search.strategy]
name = "optuna"
eval_mode = false

[search.strategy.sw_runner.ltcnn_train]
max_epochs = 30
learning_rate = 0.02
optimizer_name = "adam"
lr_gamma = 0.95
patience = 10
eval_split = "val_dataloader"
num_eval_samples = 2000

[search.strategy.hw_runner.ltcnn_area]

[search.strategy.setup]
n_jobs = 1
n_trials = 30
timeout = 172800
sampler = "nsgaii"
sum_scaled_metrics = false

[search.strategy.metrics]
accuracy.scale = 1.0
accuracy.direction = "maximize"
area_luts.scale = 1.0
area_luts.direction = "minimize"
