#!/usr/bin/env python3
"""
Emit full-pipeline DWN top-level wrappers:
  fixed_dwn_thermometer -> dwn_top (LUT stack) -> fixed_dwn_groupsum

Produces two files in the existing RTL output dir:
  full_pipeline_top.sv         — purely combinational (Vivado OOC gives 0 LUTs)
  full_pipeline_top_clocked.sv — registered pipeline with FF stages (synthesisable)

Also copies thermometer, groupsum, and clocked layer component SV files into the dir.

Usage:
    conda run -n plena2 python scripts/emit_full_pipeline_rtl.py --ckpt-name baseline_n6
    # then on beholder0:
    # vivado -mode batch -source synth_dwn.tcl \\
    #   -tclargs <rtl_dir> <results_dir> xcvu9p-flgb2104-2-i full_pipeline_top_clocked 4.0
"""
import argparse, os, sys, torch, shutil

_src = os.path.abspath(os.path.join(os.path.dirname(__file__), "../src"))
sys.path.insert(0, _src)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--ckpt-name", type=str, default="baseline_n6")
    parser.add_argument("--ckpt", type=str, default=None)
    parser.add_argument("--feature-width", type=int, default=8,
                        help="Bits per input feature in RTL (thresholds scaled accordingly)")
    parser.add_argument("--output-dir", type=str, default=None)
    return parser.parse_args()


def pack_thresholds_sv(thresholds_int, num_features, num_thresholds, feature_width):
    """Pack integer thresholds into a SystemVerilog parameter hex literal."""
    total_bits = num_features * num_thresholds * feature_width
    value = 0
    # Pack: MSB = feature 0 threshold 0, LSB = feature F-1 threshold T-1
    for f in range(num_features):
        for t in range(num_thresholds):
            thresh = int(thresholds_int[f][t]) & ((1 << feature_width) - 1)
            value = (value << feature_width) | thresh
    hex_digits = (total_bits + 3) // 4
    return f"{total_bits}'h{value:0{hex_digits}X}"


def emit_wrapper(rtl_dir, cfg, thresholds_sv, feature_width):
    num_features = cfg["input_features"]
    num_bits = cfg["num_bits"]
    num_classes = cfg["num_classes"]
    lut_output = cfg["hidden_sizes"][-1]
    thermo_bits = num_features * num_bits

    sv = f"""\
// Full DWN inference pipeline: thermometer encoding -> LUT stack -> GroupSum
// Auto-generated by scripts/emit_full_pipeline_rtl.py
// Config: input_features={num_features}, num_bits={num_bits}, num_classes={num_classes}
// Input: {num_features} features x {feature_width}-bit integers
// Thermometer output: {thermo_bits} bits -> LUT stack -> {lut_output} bits -> {num_classes} class scores

module full_pipeline_top (
    input  wire  [{num_features * feature_width - 1}:0] data_in_0,
    input  logic                             data_in_0_valid,
    output logic                             data_in_0_ready,

    output logic [$clog2({lut_output}/{num_classes}):0] data_out_0 [0:{num_classes - 1}],
    output logic                             data_out_0_valid,
    input  logic                             data_out_0_ready,

    input  wire                              clk,
    input  wire                              rst
);

    // ----------------------------------------------------------------
    // Stage 1: Thermometer encoding
    // ----------------------------------------------------------------
    wire  [{thermo_bits - 1}:0] thermo_out;
    logic                       thermo_valid;
    logic                       thermo_ready;

    fixed_dwn_thermometer #(
        .NUM_FEATURES   ({num_features}),
        .FEATURE_WIDTH  ({feature_width}),
        .NUM_THRESHOLDS ({num_bits}),
        .THRESHOLDS     ({thresholds_sv})
    ) thermo_inst (
        .data_in_0        (data_in_0),
        .data_in_0_valid  (data_in_0_valid),
        .data_in_0_ready  (data_in_0_ready),
        .data_out_0       (thermo_out),
        .data_out_0_valid (thermo_valid),
        .data_out_0_ready (thermo_ready)
    );

    // ----------------------------------------------------------------
    // Stage 2: LUT layer stack (generated dwn_top)
    // ----------------------------------------------------------------
    wire  [{lut_output - 1}:0] lut_out;
    logic                      lut_valid;
    logic                      lut_ready;

    dwn_top lut_inst (
        .clk              (clk),
        .rst              (rst),
        .data_in_0        (thermo_out),
        .data_in_0_valid  (thermo_valid),
        .data_in_0_ready  (thermo_ready),
        .data_out_0       (lut_out),
        .data_out_0_valid (lut_valid),
        .data_out_0_ready (lut_ready)
    );

    // ----------------------------------------------------------------
    // Stage 3: GroupSum output aggregation
    // ----------------------------------------------------------------
    fixed_dwn_groupsum #(
        .INPUT_SIZE ({lut_output}),
        .NUM_GROUPS ({num_classes})
    ) gs_inst (
        .data_in_0        (lut_out),
        .data_in_0_valid  (lut_valid),
        .data_in_0_ready  (lut_ready),
        .data_out_0       (data_out_0),
        .data_out_0_valid (data_out_0_valid),
        .data_out_0_ready (data_out_0_ready)
    );

endmodule
"""
    out_path = os.path.join(rtl_dir, "full_pipeline_top.sv")
    with open(out_path, "w") as f:
        f.write(sv)
    print(f"Written: {out_path}")
    return out_path


def emit_clocked_wrapper(rtl_dir, cfg, thresholds_sv, feature_width):
    """Emit full_pipeline_top_clocked.sv with FF register stages.

    Pipeline stages:
      1. fixed_dwn_thermometer (combinational)
      2. FF register: thermo_out -> thermo_reg
      3. dwn_top_clocked (FF between LUT layers)
      4. fixed_dwn_groupsum (combinational)
      5. FF register: gs_out -> data_out registers

    This design has real sequential logic so Vivado reports meaningful
    CLB LUT + FF counts and timing in OOC synthesis.
    """
    num_features = cfg["input_features"]
    num_bits = cfg["num_bits"]
    num_classes = cfg["num_classes"]
    lut_output = cfg["hidden_sizes"][-1]
    thermo_bits = num_features * num_bits
    score_width = f"$clog2({lut_output}/{num_classes})"

    sv = f"""\
// Full DWN inference pipeline — clocked/registered variant.
// Stages: thermometer (comb) -> FF reg -> dwn_top_clocked -> groupsum (comb) -> FF reg
// Auto-generated by scripts/emit_full_pipeline_rtl.py
// Config: input_features={num_features}, num_bits={num_bits}, num_classes={num_classes}
// Input : {num_features} features x {feature_width}-bit integers
// Thermo: {thermo_bits} bits  LUT stack: {lut_output} bits  Output: {num_classes} class scores

module full_pipeline_top_clocked (
    input  wire                                clk,
    input  wire                                rst,
    input  wire  [{num_features * feature_width - 1}:0] data_in_0,
    output logic [{score_width}:0]    data_out_0 [0:{num_classes - 1}]
);

    // ----------------------------------------------------------------
    // Stage 1: Thermometer encoding (combinational)
    // ----------------------------------------------------------------
    wire [{thermo_bits - 1}:0] thermo_comb;

    fixed_dwn_thermometer #(
        .NUM_FEATURES   ({num_features}),
        .FEATURE_WIDTH  ({feature_width}),
        .NUM_THRESHOLDS ({num_bits}),
        .THRESHOLDS     ({thresholds_sv})
    ) thermo_inst (
        .data_in_0        (data_in_0),
        .data_in_0_valid  (1'b1),
        .data_in_0_ready  (),
        .data_out_0       (thermo_comb),
        .data_out_0_valid (),
        .data_out_0_ready (1'b1)
    );

    // ----------------------------------------------------------------
    // Stage 2: Register thermometer output (FF boundary)
    // ----------------------------------------------------------------
    logic [{thermo_bits - 1}:0] thermo_reg;
    always_ff @(posedge clk) begin
        if (rst) thermo_reg <= '0;
        else     thermo_reg <= thermo_comb;
    end

    // ----------------------------------------------------------------
    // Stage 3: LUT layer stack — clocked variant (FFs between layers)
    // ----------------------------------------------------------------
    wire [{lut_output - 1}:0] lut_out;

    dwn_top_clocked lut_inst (
        .clk              (clk),
        .rst              (rst),
        .data_in_0        (thermo_reg),
        .data_in_0_valid  (1'b1),
        .data_in_0_ready  (),
        .data_out_0       (lut_out),
        .data_out_0_valid (),
        .data_out_0_ready (1'b1)
    );

    // ----------------------------------------------------------------
    // Stage 4: GroupSum (combinational)
    // ----------------------------------------------------------------
    wire [{score_width}:0] gs_comb [0:{num_classes - 1}];

    fixed_dwn_groupsum #(
        .INPUT_SIZE ({lut_output}),
        .NUM_GROUPS ({num_classes})
    ) gs_inst (
        .data_in_0        (lut_out),
        .data_in_0_valid  (1'b1),
        .data_in_0_ready  (),
        .data_out_0       (gs_comb),
        .data_out_0_valid (),
        .data_out_0_ready (1'b1)
    );

    // ----------------------------------------------------------------
    // Stage 5: Register outputs (FF boundary)
    // ----------------------------------------------------------------
    always_ff @(posedge clk) begin
        if (rst) begin
            for (int i = 0; i < {num_classes}; i++) data_out_0[i] <= '0;
        end else begin
            for (int i = 0; i < {num_classes}; i++) data_out_0[i] <= gs_comb[i];
        end
    end

endmodule
"""
    out_path = os.path.join(rtl_dir, "full_pipeline_top_clocked.sv")
    with open(out_path, "w") as f:
        f.write(sv)
    print(f"Written: {out_path}")
    return out_path


def emit_paper_scope_wrapper(rtl_dir, cfg):
    """Emit dwn_top_paper_scope.sv: LUT layers + pipelined GroupSum, no thermometer.

    Matches the OOC synthesis scope from Table 2 of Bacellar et al. (arXiv:2410.11112).
    Input: thermo_bits-wide already-encoded binary.
    Output: num_classes class scores.
    """
    num_classes = cfg["num_classes"]
    lut_output = cfg["hidden_sizes"][-1]
    thermo_bits = cfg["input_features"] * cfg["num_bits"]
    score_width = f"$clog2({lut_output}/{num_classes})"

    sv = f"""\
// DWN paper-scope top: LUT layers + pipelined GroupSum (no thermometer encoder)
// Matches Table 2 OOC synthesis scope from Bacellar et al. (arXiv:2410.11112)
// Auto-generated by scripts/emit_full_pipeline_rtl.py
// Input : {thermo_bits}-bit thermometer-encoded binary
// Output: {num_classes} class scores
module dwn_top_paper_scope (
    input  wire           clk,
    input  wire           rst,
    input  wire  [{thermo_bits - 1}:0] data_in_0,
    output logic [{score_width}:0] data_out_0 [0:{num_classes - 1}]
);

    wire [{lut_output - 1}:0] lut_out;
    wire                      lut_valid;

    dwn_top_clocked lut_inst (
        .clk              (clk),
        .rst              (rst),
        .data_in_0        (data_in_0),
        .data_in_0_valid  (1'b1),
        .data_in_0_ready  (),
        .data_out_0       (lut_out),
        .data_out_0_valid (lut_valid),
        .data_out_0_ready (1'b1)
    );

    fixed_dwn_groupsum_pipelined #(
        .INPUT_SIZE ({lut_output}),
        .NUM_GROUPS ({num_classes})
    ) gs_inst (
        .clk              (clk),
        .rst              (rst),
        .data_in_0        (lut_out),
        .data_in_0_valid  (lut_valid),
        .data_in_0_ready  (),
        .data_out_0       (data_out_0),
        .data_out_0_valid (),
        .data_out_0_ready (1'b1)
    );

endmodule
"""
    out_path = os.path.join(rtl_dir, "dwn_top_paper_scope.sv")
    with open(out_path, "w") as f:
        f.write(sv)
    print(f"Written: {out_path}")
    return out_path


def main():
    args = parse_args()
    ckpt_dir = os.path.join(os.path.dirname(__file__), "../mase_output/dwn")
    ckpt_path = args.ckpt or os.path.join(ckpt_dir, f"{args.ckpt_name}.pt")
    rtl_dir = args.output_dir or os.path.join(
        ckpt_dir, f"{args.ckpt_name}_rtl", "hardware", "rtl"
    )
    os.makedirs(rtl_dir, exist_ok=True)

    if os.path.exists(ckpt_path):
        print(f"Loading checkpoint: {ckpt_path}")
        ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=True)
        cfg = ckpt["model_config"]
        state = ckpt["model_state_dict"]

        thres_key = "thermometer.thresholds"
        if thres_key in state:
            # Thresholds are float in [0,1]; quantize to feature_width bits
            thresholds_float = state[thres_key]  # [num_features, num_bits]
            maxval = (1 << args.feature_width) - 1
            thresholds_int = (thresholds_float.clamp(0.0, 1.0) * maxval).round().long()
            print(f"Using fitted thresholds from checkpoint (quantized to {args.feature_width}-bit)")
        else:
            # Evenly-spaced fallback
            num_features = cfg["input_features"]
            num_bits = cfg["num_bits"]
            maxval = (1 << args.feature_width) - 1
            step = maxval // (num_bits + 1)
            thresholds_int = torch.tensor(
                [[step * (t + 1) for t in range(num_bits)] for _ in range(num_features)],
                dtype=torch.long,
            )
            print(f"No fitted thresholds in checkpoint; using evenly-spaced (step={step})")
    else:
        print(f"Checkpoint not found: {ckpt_path}; using MNIST baseline defaults")
        cfg = {"input_features": 784, "num_bits": 3, "num_classes": 10, "hidden_sizes": [2000, 1000]}
        maxval = (1 << args.feature_width) - 1
        step = maxval // (cfg["num_bits"] + 1)
        thresholds_int = torch.tensor(
            [[step * (t + 1) for t in range(cfg["num_bits"])] for _ in range(cfg["input_features"])],
            dtype=torch.long,
        )

    thresholds_sv = pack_thresholds_sv(
        thresholds_int, cfg["input_features"], cfg["num_bits"], args.feature_width
    )

    # Copy component files
    component_src = os.path.join(os.path.dirname(__file__),
                                  "../src/mase_components/dwn_layers/rtl")
    for fname in ["fixed_dwn_thermometer.sv", "fixed_dwn_groupsum.sv",
                  "fixed_dwn_lut_layer_clocked.sv", "fixed_dwn_groupsum_pipelined.sv"]:
        dst = os.path.join(rtl_dir, fname)
        shutil.copy(os.path.join(component_src, fname), dst)
        print(f"Copied: {fname}")

    emit_wrapper(rtl_dir, cfg, thresholds_sv, args.feature_width)
    emit_clocked_wrapper(rtl_dir, cfg, thresholds_sv, args.feature_width)
    emit_paper_scope_wrapper(rtl_dir, cfg)

    abs_rtl = os.path.abspath(rtl_dir)
    print(f"\nSynthesis commands (on Vivado server):")
    print(f"  # Combinational (will give 0 CLB LUTs in OOC — for reference only)")
    print(f"  vivado -mode batch -source synth_dwn.tcl \\")
    print(f"    -tclargs {abs_rtl} <results_dir> xcvu9p-flgb2104-2-i full_pipeline_top 4.0")
    print(f"")
    print(f"  # Clocked/registered — meaningful LUT + FF count")
    print(f"  vivado -mode batch -source synth_dwn.tcl \\")
    print(f"    -tclargs {abs_rtl} <results_dir> xcvu9p-flgb2104-2-i full_pipeline_top_clocked 4.0")
    print(f"")
    print(f"  # Paper-scope (LUT+GroupSum only, no thermometer) — matches Bacellar Table 2")
    print(f"  vivado -mode batch -source scripts/synth_paper_match.tcl \\")
    print(f"    -tclargs {abs_rtl} <results_dir> xcvu9p-flgb2104-2-i dwn_top_paper_scope 1.21")


if __name__ == "__main__":
    main()
