#!/usr/bin/env python3
"""
emit_flopoco_thermo.py

Generates a structural thermometer_encoder.vhd using FloPoCo IntConstantComparator
instances for each unique threshold value in the DWN baseline_n6 checkpoint.

Outputs to mase_output/dwn/baseline_n6_flopoco_real_v2/
"""
import os
import re
import sys
import subprocess
import shutil
import torch

CKPT_PATH = "mase_output/dwn/baseline_n6.pt"
SRC_DIR   = "mase_output/dwn/baseline_n6_flopoco_real"
OUT_DIR   = "mase_output/dwn/baseline_n6_flopoco_real_v2"
INPUT_BITS = 8
BATCH_SIZE = 256  # All in one Docker call to get globally unique uids
FLOPOCO_TARGET = "VirtexUltrascalePlus"
FLOPOCO_FREQ   = 700
DOCKER_IMAGE   = "flopoco-dwn:latest"


def run_flopoco_batch(batch_vals, batch_idx, out_dir):
    """Run FloPoCo Docker for a batch of threshold values. Returns output VHDL path."""
    out_filename = f"comparators_batch_{batch_idx}.vhd"
    out_path = os.path.join(out_dir, out_filename)

    # Build flopoco command string
    ops = " ".join(
        f"IntConstantComparator w={INPUT_BITS} c={v} flags=4"
        for v in batch_vals
    )
    flopoco_cmd = (
        f"flopoco target={FLOPOCO_TARGET} frequency={FLOPOCO_FREQ} "
        f"{ops} outputFile=/output/{out_filename} 2>&1"
    )

    cmd = [
        "docker", "run", "--rm",
        "--security-opt", "label=disable",
        "-v", f"{os.path.abspath(out_dir)}:/output",
        "--entrypoint", "bash",
        DOCKER_IMAGE,
        "-c", flopoco_cmd,
    ]

    print(f"  Batch {batch_idx}: {len(batch_vals)} comparators "
          f"(c={batch_vals[0]}..{batch_vals[-1]}) ...", flush=True)
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
    if result.returncode != 0:
        print(f"  Docker stdout: {result.stdout[:500]}")
        print(f"  Docker stderr: {result.stderr[:500]}")
        raise RuntimeError(f"FloPoCo batch {batch_idx} failed (rc={result.returncode})")

    if not os.path.exists(out_path):
        raise RuntimeError(f"Expected output file not found: {out_path}")

    return out_path


def parse_entity_names(vhd_path, expected_vals):
    """
    Parse entity names from a FloPoCo-generated VHDL file.
    Returns dict: thresh_val -> entity_name.
    Assumes one entity per comparator, in the same order as expected_vals.
    """
    with open(vhd_path) as fh:
        content = fh.read()

    # Match "entity <name> is" declarations
    entities = re.findall(r'entity\s+(IntConstantComparator\S+)\s+is', content)

    if len(entities) < len(expected_vals):
        print(f"  WARNING: found {len(entities)} entities but expected {len(expected_vals)}")

    mapping = {}
    for i, val in enumerate(expected_vals):
        if i < len(entities):
            mapping[val] = entities[i]
            print(f"    c={val:3d} -> {entities[i]}")
        else:
            print(f"    c={val:3d} -> MISSING (will use behavioral fallback)")

    return mapping


def generate_thermometer_vhd(out_dir, thresh_ints, entity_names, num_features, num_bits):
    """Generate the structural thermometer_encoder.vhd."""
    total_in  = num_features * INPUT_BITS
    total_out = num_features * num_bits

    thermo_file = os.path.join(out_dir, "thermometer_encoder.vhd")

    # Collect unique entity names for component declarations
    unique_entities = {}  # entity_name -> thresh_val (just need one example for comment)
    for val, ename in entity_names.items():
        if ename not in unique_entities:
            unique_entities[ename] = val

    with open(thermo_file, "w") as f:
        f.write("-- Thermometer encoder: structural VHDL using FloPoCo IntConstantComparator\n")
        f.write("-- Generated by emit_flopoco_thermo.py\n")
        f.write(f"-- Target: {FLOPOCO_TARGET} @ {FLOPOCO_FREQ} MHz\n")
        f.write(f"-- {num_features} features x {num_bits} bits = {total_out} outputs\n\n")

        f.write("library ieee;\n")
        f.write("use ieee.std_logic_1164.all;\n")
        f.write("use ieee.numeric_std.all;\n\n")

        f.write("entity thermometer_encoder is\n")
        f.write("  port (\n")
        f.write(f"    x_in  : in  std_logic_vector({total_in - 1} downto 0);\n")
        f.write(f"    x_out : out std_logic_vector({total_out - 1} downto 0)\n")
        f.write("  );\n")
        f.write("end entity thermometer_encoder;\n\n")

        f.write("architecture structural of thermometer_encoder is\n\n")

        # Component declarations
        for ename in sorted(unique_entities.keys()):
            f.write(f"  component {ename} is\n")
            f.write("    port (\n")
            f.write(f"      X    : in  std_logic_vector({INPUT_BITS - 1} downto 0);\n")
            f.write("      XgtC : out std_logic\n")
            f.write("    );\n")
            f.write(f"  end component;\n\n")

        f.write("begin\n\n")

        # Instantiate one comparator per (feature, bit) pair
        behavioral_count = 0
        for feat_i in range(num_features):
            in_hi = (feat_i + 1) * INPUT_BITS - 1
            in_lo =  feat_i      * INPUT_BITS
            for bit_j in range(num_bits):
                thresh_val = thresh_ints[feat_i, bit_j].item()
                out_idx    = feat_i * num_bits + bit_j

                if thresh_val in entity_names:
                    ename     = entity_names[thresh_val]
                    inst_name = f"cmp_f{feat_i}_b{bit_j}"
                    f.write(f"  {inst_name}: {ename}\n")
                    f.write("    port map (\n")
                    f.write(f"      X    => x_in({in_hi} downto {in_lo}),\n")
                    f.write(f"      XgtC => x_out({out_idx})\n")
                    f.write("    );\n\n")
                else:
                    # Behavioral fallback: feat > thresh_val  <=>  feat >= thresh_val+1
                    behavioral_count += 1
                    f.write(f"  -- Behavioral fallback: feat={feat_i} bit={bit_j} c={thresh_val}\n")
                    f.write(f"  x_out({out_idx}) <= '1' when "
                            f"unsigned(x_in({in_hi} downto {in_lo})) > "
                            f"to_unsigned({thresh_val}, {INPUT_BITS}) else '0';\n\n")

        f.write("end architecture structural;\n")

    if behavioral_count:
        print(f"  WARNING: {behavioral_count} comparisons used behavioral fallback")
    return thermo_file


def main():
    # ------------------------------------------------------------------ #
    # 1. Load checkpoint                                                   #
    # ------------------------------------------------------------------ #
    print(f"Loading checkpoint: {CKPT_PATH}")
    ckpt       = torch.load(CKPT_PATH, map_location="cpu")
    thresholds = ckpt["model_state_dict"]["thermometer.thresholds"]  # [784, 3]
    num_features, num_bits = thresholds.shape
    print(f"  Features: {num_features}, bits: {num_bits}")

    # ------------------------------------------------------------------ #
    # 2. Integer thresholds                                                #
    # ------------------------------------------------------------------ #
    max_val    = (1 << INPUT_BITS) - 1
    thresh_ints = (thresholds * max_val).round().clamp(0, max_val).int()
    unique_vals = sorted(set(thresh_ints.flatten().tolist()))
    print(f"  Unique threshold values: {len(unique_vals)}  "
          f"(range {unique_vals[0]}–{unique_vals[-1]})")

    # ------------------------------------------------------------------ #
    # 3. Prepare output directory                                          #
    # ------------------------------------------------------------------ #
    os.makedirs(OUT_DIR, exist_ok=True)
    print(f"\nCopying existing VHDL files from {SRC_DIR} -> {OUT_DIR}")
    copied = 0
    for fname in os.listdir(SRC_DIR):
        if fname.endswith(".vhd") and fname != "thermometer_encoder.vhd":
            shutil.copy2(os.path.join(SRC_DIR, fname), os.path.join(OUT_DIR, fname))
            copied += 1
    print(f"  Copied {copied} files (skipped thermometer_encoder.vhd)")

    # ------------------------------------------------------------------ #
    # 4. Generate IntConstantComparator VHDL via FloPoCo Docker            #
    # ------------------------------------------------------------------ #
    print(f"\nGenerating FloPoCo comparators ({len(unique_vals)} unique values, "
          f"batch size {BATCH_SIZE}) ...")
    entity_names = {}  # thresh_val -> flopoco entity name

    for batch_start in range(0, len(unique_vals), BATCH_SIZE):
        batch     = unique_vals[batch_start : batch_start + BATCH_SIZE]
        batch_idx = batch_start // BATCH_SIZE
        vhd_path  = run_flopoco_batch(batch, batch_idx, OUT_DIR)
        mapping   = parse_entity_names(vhd_path, batch)
        entity_names.update(mapping)

    found   = sum(1 for v in unique_vals if v in entity_names)
    missing = len(unique_vals) - found
    print(f"\nEntity name resolution: {found}/{len(unique_vals)} found "
          f"({'OK' if missing == 0 else f'{missing} MISSING'})")

    # ------------------------------------------------------------------ #
    # 5. Generate structural thermometer_encoder.vhd                      #
    # ------------------------------------------------------------------ #
    print(f"\nGenerating structural thermometer_encoder.vhd ...")
    thermo_file = generate_thermometer_vhd(
        OUT_DIR, thresh_ints, entity_names, num_features, num_bits
    )
    print(f"  Written: {thermo_file}")

    # ------------------------------------------------------------------ #
    # 6. Summary                                                           #
    # ------------------------------------------------------------------ #
    all_files = sorted(os.listdir(OUT_DIR))
    vhd_files = [f for f in all_files if f.endswith(".vhd")]
    print(f"\nOutput directory: {OUT_DIR}")
    print(f"  Total files : {len(all_files)}")
    print(f"  VHDL files  : {len(vhd_files)}")
    key_files = ["thermometer_encoder.vhd", "dwn_top.vhd", "popcount.vhd"]
    for kf in key_files:
        present = kf in all_files
        print(f"    {'[OK]' if present else '[MISSING]'} {kf}")


if __name__ == "__main__":
    main()
